---
title: Leonids
timezone: Europe/Paris
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: 
description: A simple and awesome blog theme powered by jekyll.
url: 
markdown: kramdown
highlighter: rouge
excerpt_separator: "<!--more-->"
permalink: "/articles/:year-:month/:title"
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
owner:
  name: Leonids
  avatar: leonids-logo.png
  job: A jekyll theme
  bio: A simple and awesome blog theme powered by jekyll.
  email: 
  disqus-shortname: 
  twitter: 
  facebook: 
  google:
    plus: 
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: 
  gitlab: 
  stackoverflow: 
  linkedin: 
  skype: 
  xing: 
  instagram: 
  lastfm: 
  tumblr: 
  pinterest: 
  foursquare: 
  steam: 
  dribbble: 
  youtube: 
  soundcloud: 
  weibo: 
  flickr: 
  500px: 
  codepen: 
